# Generated by Django 3.0.2 on 2020-01-06 07:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 6, 7, 33, 51, 667300, tzinfo=utc), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='post',
            name='modify_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 6, 7, 33, 51, 667331, tzinfo=utc), verbose_name='修改时间'),
        ),
    ]
