# Generated by Django 3.0.2 on 2020-01-07 06:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200107_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 7, 6, 35, 4, 213880, tzinfo=utc), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='post',
            name='modify_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 7, 6, 35, 4, 213913, tzinfo=utc), verbose_name='修改时间'),
        ),
    ]
