# Generated by Django 3.0.2 on 2020-01-07 07:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200107_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 7, 7, 15, 35, 705743, tzinfo=utc), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='post',
            name='modify_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 7, 7, 15, 35, 705779, tzinfo=utc), verbose_name='修改时间'),
        ),
    ]
