# Generated by Django 3.0.2 on 2020-01-09 07:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200107_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=mdeditor.fields.MDTextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 9, 7, 38, 41, 25416, tzinfo=utc), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='post',
            name='modify_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 9, 7, 38, 41, 25450, tzinfo=utc), verbose_name='修改时间'),
        ),
    ]
