# Generated by Django 3.0.2 on 2020-01-09 09:57

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200109_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 9, 9, 57, 32, 969766, tzinfo=utc), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='post',
            name='modify_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 9, 9, 57, 32, 969796, tzinfo=utc), verbose_name='修改时间'),
        ),
    ]
