# Generated by Django 3.0.2 on 2020-01-07 06:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20200107_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 7, 6, 35, 4, 215830, tzinfo=utc), verbose_name='评论时间'),
        ),
    ]
