# Generated by Django 3.0.2 on 2020-01-07 07:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20200107_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 7, 7, 15, 35, 707585, tzinfo=utc), verbose_name='评论时间'),
        ),
    ]
