# Generated by Django 3.0.2 on 2020-01-09 07:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20200107_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 9, 7, 38, 41, 27923, tzinfo=utc), verbose_name='评论时间'),
        ),
    ]
