# Generated by Django 3.0.2 on 2020-01-09 09:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20200109_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 9, 9, 40, 5, 929767, tzinfo=utc), verbose_name='评论时间'),
        ),
    ]
